language: go

go: 1.4.2

env:
  global:
    - BUILD_OS_ARCH="linux/amd64 darwin/amd64 windows/amd64"

before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -osarch="${BUILD_OS_ARCH}"

install:
  # We override the install phase to avoid the default "go get ... / godep restore"
  # because we only want the deps from Godeps
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

#before_script:
#  - go vet ./...

after_success:
  - gox -output="build/{{.OS}}/{{.Arch}}/{{.Dir}}" -osarch="${BUILD_OS_ARCH}"
